#!/bin/bash

# set the number of nodes and processes per node
#PBS -l nodes={{ nodes }}:ppn={{ processes_per_node }}

# set max wallclock time
#PBS -l walltime={{ formatted_walltime }}

# set name of job
#PBS -N {{ name }}

# mail alert at start, end and abortion of execution
#PBS -m bea

# send mail to this address
#PBS -M {{ notification_email }}

# use submission environment
#PBS -V

{% block additional_pbs_setup %}
{% endblock additional_pbs_setup %}

# start job from the directory it was submitted
cd $PBS_O_WORKDIR

module load python/2.7

pip install --user -r {{ remote_requirements_path }}

{% block prerun %}
{% endblock prerun %}

python {{ remote_package_path }} {{ model_output_path }} {{ metadata_output_path }}

{% block postrun %}
{% endblock postrun %}

